services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./models:/models
    ports:
      - "8786:8000"
    ipc: host
    command: >
      --model /models/tclf90/Qwen3-Coder-30B-A3B-Instruct-AWQ
      --served-model-name Qwen3-Coder-30B-A3B-Instruct-AWQ
      --tensor-parallel-size 2
      --max-model-len 131072
      --max-num-seqs 8
      --swap-space 32
      --gpu-memory-utilization 0.95
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --trust-remote-code