services:
  Qwen3-4B-Instruct-2507-AWQ:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./models:/models
    ports:
      - "8786:8000"
    ipc: host
    command: >
      --model /models/Eslzzyl/Qwen3-4B-Instruct-2507-AWQ
      --served-model-name Qwen3-4B-Instruct-2507-AWQ
      --api-key xxx
      --max-model-len 32768
      --max-num-seqs 1
      --swap-space 10
      --gpu-memory-utilization 0.9
      --enable-auto-tool-choice
      --tool-call-parser hermes
      --trust-remote-code
      --disable-log-requests
